apiVersion: v1
kind: Service
metadata:
  name: eve-api-v1
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: api
    - port: 3001
      targetPort: 3001
      name: metrics
  selector:
    app: eve-api-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-api-v1
  namespace: default
spec:
  selector:
    matchLabels:
      app: eve-api-v1
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
      labels:
        app: eve-api-v1
    spec:
      serviceAccountName: eve-api
      securityContext:
        runAsUser: 9001
        runAsGroup: 9001
        fsGroup: 65534
      containers:
        - name: eve-api-v1
          image: unanet-docker.jfrog.io/ops/eve-api-v1:0.1.0
          imagePullPolicy: Always
          env:
            - name: EVE_ARTIFACTORY_BASE_URL
              value: "https://unanet.jfrog.io/unanet/api"
            - name: EVE_GITLAB_BASE_URL
              value: "https://gitlab.unanet.io/api"
            - name: EVE_VAULT_ADDR
              value: "https://vault.unanet.io"
            - name: EVE_API_Q_URL
              value: "https://sqs.us-east-2.amazonaws.com/580107804399/eve-api-prod.fifo"
            - name: EVE_S3_BUCKET
              value: "unanet-eve-queue"
            - name: EVE_AWS_REGION
              value: "us-east-2"
            - name: EVE_DB_HOST
              value: "devops-prod-db.unanet.io"
            - name: EVE_DB_NAME
              value: "eve"
            - name: EVE_LOG_LEVEL
              value: "info"
            - name: EVE_ARTIFACTORY_API_KEY
              value: vault:devops/eve#EVE_ARTIFACTORY_API_KEY
            - name: EVE_DB_PASSWORD
              value: vault:devops/eve#EVE_DB_PASSWORD
            - name: EVE_DB_USERNAME
              value: vault:devops/eve#EVE_DB_USERNAME
            - name: EVE_GITLAB_API_KEY
              value: vault:devops/eve#EVE_GITLAB_API_KEY
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 3001
              name: metrics
      imagePullSecrets:
        - name: docker-cfg
