apiVersion: batch/v1
kind: Job
metadata:
  name: eve-api-v1-migration
  namespace: default
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-env: "kv/data/devops/eve"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "kv/data/devops/eve" -}}
          {{ range $k, $v := .Data.data }}
          export {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}
        vault.hashicorp.com/role: "k8s-devops"
      labels:
        app: eve-api-v1-migration
    spec:
      containers:
        - name: eve-api-v1-migration
          image: unanet-docker.jfrog.io/eve-api:0.1.0
          imagePullPolicy: Always
          args: ["/app/eve-api", "-migrate", "-drop"]
          env:
            - name: EVE_DB_HOST
              value: "devops-prod-eve-db.unanet.io"
            - name: EVE_DB_NAME
              value: "eve"
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-cfg
  backoffLimit: 4