stages:
  - build

build:
  stage: build
  script:
    - make
  tags:
    - linux
  except:
    - tags
    - master

dist:
  stage: build
  script:
    - make dist
  tags:
    - linux
  only: master
  