version: "3.7"

services:
  eve-api:
    image: unanet-docker.jfrog.io/eve-api:0.1.0
    container_name: eve_api
    environment:
      - EVE_ARTIFACTORY_API_KEY=${EVE_ARTIFACTORY_API_KEY}
      - EVE_ARTIFACTORY_BASE_URL=${EVE_ARTIFACTORY_BASE_URL}
      - EVE_SERVICE_NAME=eve-api
      - EVE_DB_HOST=db
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      - eve-net
    links:
      - eve-db:db
    depends_on:
      - eve-db

  eve-db:
    image: postgres:11.4
    container_name: eve_db
    ports:
      - "5432:5432"
    networks:
      - eve-net
    environment:
      - POSTGRES_USER=eve-api
      - POSTGRES_PASSWORD=eve-api

networks:
  eve-net: