version: "3.7"

services:
  eve-db:
    image: postgres:11.4
    container_name: eve_db
    ports:
      - "5432:5432"
    networks:
      - eve-net
    environment:
      - POSTGRES_USER=eve-api
      - POSTGRES_PASSWORD=eve-api

networks:
  eve-net: