---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-api-v1
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: eve-api-v1
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
      labels:
        app: eve-api-v1
        metrics: enabled
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      securityContext:
        runAsUser: 9001
        runAsGroup: 9001
        fsGroup: 65534
      containers:
        - name: eve-api-v1
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: EVE_ARTIFACTORY_BASE_URL
              value: {{ .Values.eveArtifactoryBaseURL }}
            - name: EVE_ARTIFACTORY_API_KEY
              value: {{ .Values.eveArtifactoryAPIKey }}
            - name: GITLAB_BASE_URL
              value: {{ .Values.eveGitlabBaseURL }}
            - name: API_Q_URL
              value: {{ .Values.eveApiQUrl }}
            - name: S3_BUCKET
              value: {{ .Values.eveS3Bucket }}
            - name: DB_HOST
              value: {{ .Values.eveDBHost }}
            - name: DB_NAME
              value: {{ .Values.eveDBName }}
            - name: DB_PASSWORD
              value: {{ .Values.eveDBPassword }}
            - name: DB_USERNAME
              value: {{ .Values.eveDBUsername }}
            - name: AWS_ACCESS_KEY
              value: {{ .Values.eveAWSAccessKey }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.eveAWSSecretKey }}
            - name: AWS_REGION
              value: {{ .Values.eveAWSRegion }}
            - name: LOG_LEVEL
              value: {{ .Values.eveLogLevel }}
            - name: GITLAB_API_KEY
              value: {{ .Values.eveGitlabAPIKey }}
            - name: GITHUB_ACCESS_TOKEN
              value: {{ .Values.eveGithubAccessToken }}
            - name: GITHUB_BASE_URL
              value: {{ .Values.eveGithubBaseURL }}
            - name: VAULT_ROLE
              value: {{ .Values.vaultRole }}
            - name: VAULT_ADDR
              value: {{ .Values.vaultAddr }}
            - name: VAULT_K8S_MOUNT
              value: {{ .Values.vaultK8sMount }}
            - name: ADMIN_TOKEN
              value: {{ .Values.eveAdminToken }}
            - name: PROVIDER_TYPE
              value: {{ .Values.secretsProviderType }}
            - name: DYNAMIC_SECRETS_ENABLED
              value: {{ .Values.dynamicSecretsEnabled | quote }}              
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 3001
              name: metrics
      imagePullSecrets:
        - name: docker-cfg
