---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-api-v1
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: eve-api-v1
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
      labels:
        app: eve-api-v1
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      securityContext:
        runAsUser: 9001
        runAsGroup: 9001
        fsGroup: 65534
      containers:
        - name: eve-api-v1
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: EVE_ARTIFACTORY_BASE_URL
              value: {{ .Values.eveArtifactoryBaseURL }}
            - name: EVE_GITLAB_BASE_URL
              value: {{ .Values.eveGitlabBaseURL }}
            - name: EVE_API_Q_URL
              value: {{ .Values.eveApiQUrl }}
            - name: EVE_S3_BUCKET
              value: {{ .Values.eveS3Bucket }}
            - name: EVE_AWS_REGION
              value: {{ .Values.eveAWSRegion }}
            - name: EVE_DB_HOST
              value: {{ .Values.eveDBHost }}
            - name: EVE_DB_NAME
              value: {{ .Values.eveDBName }}
            - name: EVE_LOG_LEVEL
              value: {{ .Values.eveLogLevel }}
            - name: EVE_ARTIFACTORY_API_KEY
              value: {{ .Values.eveArtifactoryAPIKey }}
            - name: EVE_DB_PASSWORD
              value: {{ .Values.eveDBPassword }}
            - name: EVE_DB_USERNAME
              value: {{ .Values.eveDBUsername }}
            - name: EVE_GITLAB_API_KEY
              value: {{ .Values.eveGitlabAPIKey }}
            - name: VAULT_ROLE
              value: {{ .Values.vaultRole }}
            - name: VAULT_ADDR
              value: {{ .Values.vaultAddr }}
            - name: VAULT_K8S_MOUNT
              value: {{ .Values.vaultK8sMount }}              
          ports:
            - containerPort: 3000
              name: api
            - containerPort: 3001
              name: metrics
      imagePullSecrets:
        - name: docker-cfg
