eveApiQUrl: ""
eveS3Bucket: ""
eveAWSRegion: ""
eveAWSSecretKey: ""
eveAWSAccessKey: ""
eveDBHost: ""
eveDBName: ""
eveLogLevel: ""
eveGithubAccessToken: ""
serviceAccount: ""
image: ""
eveArtifactoryAPIKey: ""
eveDBPassword: ""
eveDBUsername: ""
eveGitlabAPIKey: ""
eveArtifactoryBaseURL: ""
eveGitlabBaseURL: ""
vaultAddr: ""
vaultK8sMount: ""
vaultRole: ""
eveAdminToken: ""
eveGithubBaseURL: ""