eveApiQUrl: "https://sqs.us-east-2.amazonaws.com/580107804399/eve-api-prod.fifo"
eveS3Bucket: "unanet-eve-queue"
eveAWSRegion: "us-east-2"
eveDBHost: "devops-prod-db.unanet.io"
eveDBName: "eve"
eveLogLevel: "debug"
vaultAddr: "http://vault.vault:8200"
vaultK8sMount: "kubernetes"
serviceAccount: "eve-api"
image: "unanet-docker-int.jfrog.io/ops/eve-api-v1:0.1.0"
eveArtifactoryAPIKey: ""
vaultRole: ""
eveDBPassword: ""
eveDBUsername: ""
eveGitlabAPIKey: ""
eveArtifactoryBaseURL: "https://unanet.jfrog.io/unanet/api"
eveGitlabBaseURL: "https://gitlab.unanet.io/api"
eveVaultAddr: "https://vault.unanet.io"

