name: Eve CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-n-push:
    env:
      GOOS: linux
      GOARCH: amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - run: go version

      - name: Set variables ✨
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          TS=$(date -u +%F_%TUTC)
          echo "BUILD_TIME=$TS" >> $GITHUB_ENV
      - name: Test & Build 🧠
        run: |
          go get ./...
          go test ./... -v -race
          mkdir bin
          CGO_ENABLED=0 go build -ldflags="-X 'github.com/unanet/eve/internal/api/api.Version=${{ env.VERSION }}.${{ github.run_number }}'" -o ./bin/eve-api ./cmd/eve-api/main.go

      - name: Set up Docker Buildx 🐳
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Docker layers 🐳
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Check SemVer Tag 🖖
        run: |
          echo "${{ env.VERSION }}"
          make check_version

      - name: Docker Image 🐳
        if: ${{ contains(github.ref, 'master') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            unanet/eve:latest
            unanet/eve:${{ env.VERSION }}
